import "~/styles/globals.css";
import { cn } from "~/lib/utils";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import {Inter} from "next/font/google"
import NavBar from "~/components/NavBar";
import { ThemeProvider } from "next-themes";
import { Toaster } from "../components/ui/sonner"
const inter=Inter({subsets:["latin"]})

export const metadata: Metadata = {
  title: "Quiz App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className={cn(inter.className)}>
        
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
      >
        <NavBar/>
        
        {children}
        <Toaster />
        </ThemeProvider>
        
        </body>
      
    </html>
  );
}
